# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/workdir/software/github/zstd

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/workdir/software/github/zstd

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/workdir/software/github/zstd/CMakeFiles /home/user/workdir/software/github/zstd/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/workdir/software/github/zstd/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) -f build/cmake/CMakeFiles/clean-all.dir/build.make build/cmake/CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

#=============================================================================
# Target rules for targets named libzstd_static

# Build rule for target.
libzstd_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libzstd_static
.PHONY : libzstd_static

# fast build rule for target.
libzstd_static/fast:
	$(MAKE) -f build/cmake/lib/CMakeFiles/libzstd_static.dir/build.make build/cmake/lib/CMakeFiles/libzstd_static.dir/build
.PHONY : libzstd_static/fast

#=============================================================================
# Target rules for targets named libzstd_shared

# Build rule for target.
libzstd_shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libzstd_shared
.PHONY : libzstd_shared

# fast build rule for target.
libzstd_shared/fast:
	$(MAKE) -f build/cmake/lib/CMakeFiles/libzstd_shared.dir/build.make build/cmake/lib/CMakeFiles/libzstd_shared.dir/build
.PHONY : libzstd_shared/fast

#=============================================================================
# Target rules for targets named libzstd.pc

# Build rule for target.
libzstd.pc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libzstd.pc
.PHONY : libzstd.pc

# fast build rule for target.
libzstd.pc/fast:
	$(MAKE) -f build/cmake/lib/CMakeFiles/libzstd.pc.dir/build.make build/cmake/lib/CMakeFiles/libzstd.pc.dir/build
.PHONY : libzstd.pc/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f build/cmake/lib/CMakeFiles/uninstall.dir/build.make build/cmake/lib/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named zstd-frugal

# Build rule for target.
zstd-frugal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zstd-frugal
.PHONY : zstd-frugal

# fast build rule for target.
zstd-frugal/fast:
	$(MAKE) -f build/cmake/programs/CMakeFiles/zstd-frugal.dir/build.make build/cmake/programs/CMakeFiles/zstd-frugal.dir/build
.PHONY : zstd-frugal/fast

#=============================================================================
# Target rules for targets named unzstd.1

# Build rule for target.
unzstd.1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unzstd.1
.PHONY : unzstd.1

# fast build rule for target.
unzstd.1/fast:
	$(MAKE) -f build/cmake/programs/CMakeFiles/unzstd.1.dir/build.make build/cmake/programs/CMakeFiles/unzstd.1.dir/build
.PHONY : unzstd.1/fast

#=============================================================================
# Target rules for targets named zstdmt

# Build rule for target.
zstdmt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zstdmt
.PHONY : zstdmt

# fast build rule for target.
zstdmt/fast:
	$(MAKE) -f build/cmake/programs/CMakeFiles/zstdmt.dir/build.make build/cmake/programs/CMakeFiles/zstdmt.dir/build
.PHONY : zstdmt/fast

#=============================================================================
# Target rules for targets named zstdcat.1

# Build rule for target.
zstdcat.1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zstdcat.1
.PHONY : zstdcat.1

# fast build rule for target.
zstdcat.1/fast:
	$(MAKE) -f build/cmake/programs/CMakeFiles/zstdcat.1.dir/build.make build/cmake/programs/CMakeFiles/zstdcat.1.dir/build
.PHONY : zstdcat.1/fast

#=============================================================================
# Target rules for targets named zstdcat

# Build rule for target.
zstdcat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zstdcat
.PHONY : zstdcat

# fast build rule for target.
zstdcat/fast:
	$(MAKE) -f build/cmake/programs/CMakeFiles/zstdcat.dir/build.make build/cmake/programs/CMakeFiles/zstdcat.dir/build
.PHONY : zstdcat/fast

#=============================================================================
# Target rules for targets named zstd

# Build rule for target.
zstd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zstd
.PHONY : zstd

# fast build rule for target.
zstd/fast:
	$(MAKE) -f build/cmake/programs/CMakeFiles/zstd.dir/build.make build/cmake/programs/CMakeFiles/zstd.dir/build
.PHONY : zstd/fast

#=============================================================================
# Target rules for targets named unzstd

# Build rule for target.
unzstd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unzstd
.PHONY : unzstd

# fast build rule for target.
unzstd/fast:
	$(MAKE) -f build/cmake/programs/CMakeFiles/unzstd.dir/build.make build/cmake/programs/CMakeFiles/unzstd.dir/build
.PHONY : unzstd/fast

#=============================================================================
# Target rules for targets named zstdgrep.1

# Build rule for target.
zstdgrep.1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zstdgrep.1
.PHONY : zstdgrep.1

# fast build rule for target.
zstdgrep.1/fast:
	$(MAKE) -f build/cmake/programs/CMakeFiles/zstdgrep.1.dir/build.make build/cmake/programs/CMakeFiles/zstdgrep.1.dir/build
.PHONY : zstdgrep.1/fast

#=============================================================================
# Target rules for targets named zstd.1

# Build rule for target.
zstd.1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zstd.1
.PHONY : zstd.1

# fast build rule for target.
zstd.1/fast:
	$(MAKE) -f build/cmake/programs/CMakeFiles/zstd.1.dir/build.make build/cmake/programs/CMakeFiles/zstd.1.dir/build
.PHONY : zstd.1/fast

#=============================================================================
# Target rules for targets named zstdless.1

# Build rule for target.
zstdless.1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zstdless.1
.PHONY : zstdless.1

# fast build rule for target.
zstdless.1/fast:
	$(MAKE) -f build/cmake/programs/CMakeFiles/zstdless.1.dir/build.make build/cmake/programs/CMakeFiles/zstdless.1.dir/build
.PHONY : zstdless.1/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... clean-all"
	@echo "... libzstd_static"
	@echo "... libzstd_shared"
	@echo "... libzstd.pc"
	@echo "... uninstall"
	@echo "... zstd-frugal"
	@echo "... unzstd.1"
	@echo "... zstdmt"
	@echo "... zstdcat.1"
	@echo "... zstdcat"
	@echo "... zstd"
	@echo "... unzstd"
	@echo "... zstdgrep.1"
	@echo "... zstd.1"
	@echo "... zstdless.1"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

